name: Devcontainer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # To ensure since_last_remote_commit works on initial PR open

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/neilenns/devcontainers/monorepo
          cacheFrom: ghcr.io/neilenns/devcontainers/monorepo
          configFile: monorepo/devcontainer.json
          refFilterForPush: refs/heads/main
          push: filter
